login and forget password page
FWB-Creators/WeCooked-Frontend pull request #6
Opened 2024-10-11 16:55 UTC by tong788

I have add login and forget password page. Additionally adding some more picture (png file) and logo in login page (svg file).

2024-10-11 21:09 UTC, Billy19191 commented
I was hoping you wouldn't request a review from me, I am on vacation.

2024-10-13 16:53 UTC, Billy19191 reviewed
Just sharing some info with you, not sure if your PR is ready to review yet. Also, please see a preliminary review from rabbit bot.

2024-10-13 16:53 UTC, Billy19191 commented on app/client/components/Forget_password.tsx
> +export default function Forget_password() {
Just so you know, always set name of components as `PascalCase`.

2024-10-13 19:56 UTC, tong788 commented on app/client/login/page.tsx
> +export default function login() {
If I change the name it will have conflict with the other file I have set up before.

2024-10-13 19:59 UTC, tong788 commented on app/client/login/forget-password/page.tsx
> +}
I have deleted div, but the name of function I did not change it due to same reason with above one.

2024-10-13 20:45 UTC, sikares commented on app/client/login/forget-password/page.tsx
> +  )
Use Fragment
https://react.dev/reference/react/Fragment

2024-10-13 20:45 UTC, sikares commented on app/client/login/page.tsx
> +}
Use Fragment
https://react.dev/reference/react/Fragment

2024-10-13 20:45 UTC, sikares commented on public/images/burger_2.png
Why do you import burger_2?
In the folder /images, we already have burger.png. Why you don't use the same picture?

2024-10-13 20:45 UTC, sikares commented on public/images/pasta_2.png
Why do you import pasta_2?
In the folder /images, we already have pasta.png. Why you don't use the same picture?

2024-10-13 20:45 UTC, sikares commented on public/images/steak_2.png
Same from above comment.

2024-10-13 20:45 UTC, sikares commented on public/images/waffle_2.png
Same from the above comment.

2024-10-13 21:06 UTC, tong788 commented on app/client/login/page.tsx
> +}
Already fix that!

2024-10-13 21:06 UTC, tong788 commented on app/client/login/forget-password/page.tsx
> +  )
Already fix that too!

2024-10-13 21:18 UTC, tong788 commented on public/images/burger_2.png
because it is a y-axis reflection(you can see in forget password page), I do not know the command to reflect the picture so I choose to import another one.

2024-10-13 21:18 UTC, tong788 commented on public/images/pasta_2.png
Same reason with above comment

2024-10-13 21:19 UTC, tong788 commented on public/images/steak_2.png
Same reason with above comment

2024-10-13 21:19 UTC, tong788 commented on public/images/waffle_2.png
Same reason with above comment

2024-10-13 21:21 UTC, tong788 commented on app/client/components/Forget_password.tsx
> +export default function Forget_password() {
Done bro

2024-10-15 19:24 UTC, tong788 commented on app/client/components/Forget_password.tsx
> +        </div>
Already set up onSubmit function logic. When click sent reset link, there will be the email within the console.log

2024-10-16 05:07 UTC, tong788 commented on app/client/login/forget-password/page.tsx
> +}
Already implement it.

2024-10-16 05:20 UTC, tong788 commented on app/client/components/Forget_password.tsx
> +      </div>
Why do I need to use aria-hidden:true?

2024-10-16 19:11 UTC, tong788 commented on app/client/components/Forget_password.tsx
> +      </div>
Done it, but i did not do responsive because it takes lot of time and it may effect to late work.

2024-10-16 19:26 UTC, tong788 commented on app/client/components/Forget_password.tsx
> +}
Done it, but i did not make email validation error for now.

2024-10-16 20:01 UTC, tong788 commented
For handlerror of login and forget password page, I will do it later

2024-10-26 17:08 UTC, Billy19191 requested changes
Change PR format to align with template

2024-10-26 18:23 UTC, tong788 commented on app/client/components/RecentlyCourse.tsx
> +        Recently course
fix it already

2024-10-26 18:46 UTC, tong788 commented on app/client/components/RecentlyCourse.tsx
>        </div>
It is in homepage I will fix in another PR.

2024-10-26 18:46 UTC, tong788 commented on app/client/components/RecentlyCourse.tsx
> +  )
It is in homepage I will fix in another PR.

2024-10-26 18:47 UTC, tong788 commented on app/client/components/Client_review.tsx
> +        </div>
It is in homepage I will fix in another PR.

2024-10-26 18:48 UTC, tong788 commented on app/client/components/ForgetPassword.tsx
> +  const [error, setError] = useState('')
I fix it already.

2024-10-26 18:57 UTC, tong788 commented on app/client/components/ForgetPassword.tsx
> +        </form>
Not necessary for our project.

2024-10-26 19:00 UTC, tong788 commented on app/client/components/ForgetPassword.tsx
> +        ></input>
not that necessary in our project scope

2024-10-26 19:01 UTC, tong788 commented on app/client/components/ForgetPassword.tsx
> +  }
Not that necessary in our project scope.

2024-10-27 03:33 UTC, tong788 commented on app/client/components/RecentlyCourse.tsx
> +import { courses } from '../data/most-popular-course'
It is in homepage I will fix in another PR.

2024-10-27 03:34 UTC, tong788 commented on app/client/components/MostPopularCourse.tsx
> +}
It is in homepage I will fix in another PR.

2024-10-27 03:37 UTC, tong788 commented on app/client/components/MostPopularCourse.tsx
> +      </div>
fix it

2024-10-27 03:42 UTC, tong788 commented on app/page.tsx
> +      <Footer />
Fixed it

2024-10-27 03:42 UTC, tong788 commented on app/page.tsx
> +import Footer from './client/components/Footer'
Fixed it

2024-10-27 03:43 UTC, tong788 commented on app/client/home/page.tsx
> +import Contact_us from '../components/Contact_us'
Fixed it

2024-10-27 03:54 UTC, tong788 commented on app/client/data/recommended-for-you.ts
> +]
It is in homepage I will fix in another PR.

2024-10-27 04:01 UTC, tong788 commented on app/client/data/recommended-for-you.ts
> +]
It is in homepage I will fix in another PR.

2024-10-27 04:02 UTC, tong788 commented on app/client/components/Contact_us.tsx
> +      </div>
It is in homepage I will fix in another PR.

2024-10-27 04:03 UTC, tong788 commented on app/client/components/Contact_us.tsx
> +      </div>
It is in homepage I will fix in another PR.

2024-10-27 04:03 UTC, tong788 commented on app/client/components/Footer.tsx
> +        </div>
It is in homepage I will fix in another PR.

2024-10-27 04:03 UTC, tong788 commented on app/client/components/Footer.tsx
> +      </div>
It is in homepage I will fix in another PR.

2024-10-27 04:04 UTC, tong788 commented on app/client/components/Client_review.tsx
> +            </div>
It is in homepage I will fix in another PR.

2024-10-27 04:04 UTC, tong788 commented on app/client/components/Client_review.tsx
> +        ))}
It is in homepage I will fix in another PR.

2024-10-27 04:04 UTC, tong788 commented on app/client/components/Client_review.tsx
> +export default function client_review() {
It is in homepage I will fix in another PR.

2024-10-27 04:05 UTC, tong788 commented on app/client/components/Client_review.tsx
> +}
It is in homepage I will fix in another PR.

2024-10-27 04:05 UTC, tong788 commented on app/client/components/Client_review.tsx
> +              />
It is in homepage I will fix in another PR.

2024-10-27 04:05 UTC, tong788 commented on app/client/components/Footer.tsx
> +        </div>
It is in homepage I will fix in another PR.

2024-10-27 04:07 UTC, tong788 commented on app/client/components/Footer.tsx
> +        </div>
It is in homepage I will fix in another PR.

2024-10-27 07:28 UTC, tong788 commented on app/client/components/RecentCourses.tsx
> +export default function RecentlyCourse() {
I will fix it in another PR since it is in main page component.

2024-10-27 07:28 UTC, tong788 commented on app/client/components/RecentCourses.tsx
> +      </h1>
I will fix it in another PR since it is in main page component.

2024-10-27 07:28 UTC, tong788 commented on app/client/components/RecentCourses.tsx
> +import { courses } from '../data/most-popular-course'
I will fix it in another PR since it is in main page component.

2024-10-27 07:28 UTC, tong788 commented on app/client/components/RecentCourses.tsx
> +  )
I will fix it in another PR since it is in main page component.

2024-10-27 07:29 UTC, tong788 commented on app/client/components/ContactUs.tsx
> +export default function Contact_us() {
I will fix it in another PR since it is in main page component.

2024-10-27 07:29 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +        </div>
I will fix it in another PR since it is in main page component.

2024-10-27 07:29 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +        </div>
I will fix it in another PR since it is in main page component.

2024-10-27 07:30 UTC, tong788 commented on app/client/home/page.tsx
> +}
I will fix it in another PR since it is in main page component.

2024-10-27 07:30 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +export default function client_review() {
I will fix it in another PR since it is in main page component.

2024-10-27 07:30 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +      </div>
I will fix it in another PR since it is in main page component.

2024-10-27 07:30 UTC, tong788 commented on app/client/home/page.tsx
> +import Footer from '../components/Footer'
I will fix it in another PR since it is in main page component.

2024-10-27 07:30 UTC, tong788 commented on app/client/components/ContactUs.tsx
> +      </div>
I will fix it in another PR since it is in main page component.

2024-10-27 07:30 UTC, tong788 commented on app/client/components/ContactUs.tsx
> +        />
I will fix it in another PR since it is in main page component.

2024-10-27 07:56 UTC, tong788 commented
@Billy19191 I have changed what you have requested to me. Can you check it again for me?

2024-10-27 10:51 UTC, Billy19191 reviewed
Drop some comments, also for all name like camelCase thing or else, please fix in this PR since you can change in this

2024-10-27 10:51 UTC, Billy19191 commented on .vscode/settings.json
Remove this file.

2024-10-27 10:51 UTC, Billy19191 commented on app/client/components/ClientReview.tsx
> +export default function client_review() {
Don't forget to change @tong788

2024-10-27 10:51 UTC, Billy19191 commented on app/client/components/ClientReview.tsx
> +          <CourseCard key={index} {...course} />
Why don't pass it through parameter?

2024-10-27 10:51 UTC, Billy19191 commented on app/client/components/ContactUs.tsx
> +        CONTACT US
Why this is only uppercase?

2024-10-27 10:51 UTC, Billy19191 commented on app/client/components/Footer.tsx
> +          <ul className="duration-300 cursor-pointer hover:text-lg hover:text-transparent bg-clip-text bg-gradient-to-t from-[#FE3511] to bg-[#F0725C]">
Use array of menu and loop instead (mapping array) because all are same element details for all `<ul>`

2024-10-27 10:51 UTC, Billy19191 commented on app/client/components/Footer.tsx
> +        Copyright ©2021 Seven spices
Remove or change to WeCooked

2024-10-27 10:51 UTC, Billy19191 commented on app/client/components/ForgetPassword.tsx
> +  const [email, setEmail] = useState('')
Add generic type to useState like 
```suggestion
  const [email, setEmail] = useState<string>('')
```

2024-10-27 10:51 UTC, Billy19191 commented on app/client/components/Login.tsx
> +  const [showPassword, setShowPassword] = useState(false)
```suggestion
  const [showPassword, setShowPassword] = useState<boolean>(false)
```

2024-10-27 10:51 UTC, Billy19191 commented on app/client/components/Login.tsx
> +  const [Remember, setRemember] = useState(false)
```suggestion
  const [Remember, setRemember] = useState<boolean>(false)
```

2024-10-27 10:51 UTC, Billy19191 commented on app/client/components/Login.tsx
> +  const [email, setEmail] = useState('')
Add generic type for all `useState`

2024-10-27 10:51 UTC, Billy19191 commented on app/client/login/forget-password/page.tsx
> +export default function forgetpassword() {
Change component name to camelCase

2024-10-27 10:54 UTC, Billy19191 commented on app/client/components/Forget_password.tsx
> +export default function Forget_password() {
Not sure you push yet? I don't see new change

2024-10-27 12:28 UTC, tong788 commented on .vscode/settings.json
Done it

2024-10-27 12:33 UTC, tong788 commented on app/client/components/ContactUs.tsx
> +        CONTACT US
![image](https://github.com/user-attachments/assets/4aaa1dfc-eb8e-4404-9ec3-206c4c2f7342)
Ux/ui team designed Figma like this.

2024-10-27 12:35 UTC, tong788 commented on app/client/components/Footer.tsx
> +        Copyright ©2021 Seven spices
Already changed to WeCooked

2024-10-27 12:39 UTC, tong788 commented on app/client/components/Login.tsx
> +  const [showPassword, setShowPassword] = useState(false)
Done it

2024-10-27 12:39 UTC, tong788 commented on app/client/components/Login.tsx
> +  const [Remember, setRemember] = useState(false)
Done it

2024-10-27 12:52 UTC, tong788 commented on app/client/login/forget-password/page.tsx
> +export default function forgetpassword() {
Last time, you told me to do Pascalcase, so I wonder which one should be used?
![image](https://github.com/user-attachments/assets/a00a3a97-e03d-458b-ba16-8759f09fc3ca)

2024-10-27 12:57 UTC, tong788 commented on app/client/components/Login.tsx
> +  const [email, setEmail] = useState('')
Done it

2024-10-27 12:58 UTC, Billy19191 commented on app/client/login/forget-password/page.tsx
> +export default function forgetpassword() {
Ah, PascalCase. My bad (but your code is not both)

![image](https://github.com/user-attachments/assets/101bf544-7d32-4756-8726-c4ab5467a4e8)

2024-10-27 13:02 UTC, tong788 commented on app/client/login/forget-password/page.tsx
> +export default function forgetpassword() {
OK OK. I changed it all to PascalCase now

2024-10-27 13:32 UTC, tong788 commented on app/client/components/Footer.tsx
> +          <ul className="duration-300 cursor-pointer hover:text-lg hover:text-transparent bg-clip-text bg-gradient-to-t from-[#FE3511] to bg-[#F0725C]">
Done it

2024-10-27 13:44 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +          <CourseCard key={index} {...course} />
@sikares Can you answer this? because you have done this part.

2024-10-27 13:47 UTC, tong788 commented on app/client/components/Forget_password.tsx
> +export default function Forget_password() {
Gonna push after finishing these comments

2024-10-27 13:56 UTC, Billy19191 approved these changes

2024-10-27 14:07 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +          <CourseCard key={index} {...course} />
Gonna change it to parameter format later

2024-10-27 14:51 UTC, sikares reviewed
Please ำdit according to the comments.

2024-10-27 14:51 UTC, sikares commented on app/client/components/ClientReview.tsx
> +          height={100}
Why don't you use width equal to height?

Fix your code.

2024-10-27 14:51 UTC, sikares commented on app/client/components/ClientReview.tsx
> +            <div className="font-bold">Gimmanee</div>
Pls change to match Figma UI.

Fix your code.

2024-10-27 14:51 UTC, sikares commented on app/client/components/ClientReview.tsx
> +          className=" size-[277px]"
Is it necessary to use size-[277px], why don't you change the width and height?

Fix your code.

2024-10-27 14:51 UTC, sikares commented on app/client/components/ContactUs.tsx
> +          className="size-[32rem]"
Is it necessary to use size-[32rem], why don't you change the width and height?
And why use rem, why not px?

Fix your code.

2024-10-27 14:51 UTC, sikares commented on app/client/components/ContactUs.tsx
> +          className="size-[32rem]"
Is it necessary to use size-[32rem], why don't you change the width and height?
And why use rem, why not px?

Fix your code.

2024-10-27 14:51 UTC, sikares commented on app/client/components/Footer.tsx
> +              width={120}
Why don't you use width equal to height?

Fix your code.

2024-10-27 14:51 UTC, sikares commented on app/client/login/page.tsx
> +import { ErrorBoundary } from 'react-error-boundary'
What is react-error-boundary, why do you use it?

2024-10-27 14:51 UTC, sikares commented on app/client/login/page.tsx
> +        <Suspense fallback={<div>Loading...</div>}>
Something went wrong and Loading... isn't in Figma, why use it?

2024-10-27 14:51 UTC, sikares commented on app/client/components/ClientReview.tsx
> +          <br />
It isn't necessary to use br

Fix your code.

2024-10-27 14:51 UTC, sikares commented on app/client/components/Login.tsx
> +            className="w-[171px] h-[120px]"
width={20}
height={20}
Why do you not use it?
Why use className="w-[171px] h-[120px]"?

Fix your code.

2024-10-27 14:51 UTC, tong788 commented on app/client/components/Footer.tsx
> +          ))}
Will consider it.

2024-10-27 15:16 UTC, tong788 commented on app/client/login/page.tsx
> +import { ErrorBoundary } from 'react-error-boundary'
CodeRabbit suggested me to put it. It is a boundary that prevent DOM tree from error when particular error occur. Consequently, the other component still can show although there is an error in this component.

2024-10-27 15:23 UTC, tong788 commented on app/client/components/ContactUs.tsx
> +          className="size-[32rem]"
I used by my consideration. I think there is no right or wrong method of sizing. But I can change it if you want.
![image](https://github.com/user-attachments/assets/de222262-62af-4ca5-a5f8-7e45f9826436)

2024-10-27 15:30 UTC, tong788 commented on app/client/components/ContactUs.tsx
> +          className="size-[32rem]"
Fixed it already, same reason with above comment.

2024-10-27 15:31 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +          <br />
OK OK

2024-10-27 15:41 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +          <br />
I have fixed it to be easier to read using className="break-words".

2024-10-27 15:43 UTC, tong788 commented on app/client/login/page.tsx
> +        <Suspense fallback={<div>Loading...</div>}>
Code rabbit suggest me to do in case of loading page takes too long or error cases, so user can know what happened

2024-10-27 15:49 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +          className=" size-[277px]"
Fixed it.

2024-10-27 15:53 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +            <div className="font-bold">Gimmanee</div>
Ok Ok

2024-10-27 15:54 UTC, tong788 commented on app/client/components/Login.tsx
> +            className="w-[171px] h-[120px]"
Fixed it.

2024-10-27 15:57 UTC, tong788 commented on app/client/components/Footer.tsx
> +              width={120}
Fixed it

2024-10-27 15:57 UTC, tong788 commented on app/client/components/ClientReview.tsx
> +          height={100}
Fixed it

2024-10-27 16:02 UTC, tong788 commented on app/client/components/Footer.tsx
> +  ]
I will fix it in another PR [WC-39].

2024-10-27 16:02 UTC, tong788 commented on app/client/components/NavbarAfter.tsx
> +  }, [])
I will fix it in another PR [WC-39].

2024-10-27 16:03 UTC, merged